/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SchedulePost': ApiRouteHandler<{ draftId: string; scheduledFor: string }, unknown, never>
    'GenerateWeeklyDigest': CronHandler<{ topic: 'draft.created'; data: never }>
    'CronTicker': CronHandler<{ topic: 'post.due'; data: never }>
    'PublishPost': EventHandler<never, never>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'GithubWebhook': ApiRouteHandler<{ action?: string; pull_request?: { merged?: boolean; title: string; body: string | unknown; html_url: string; url: string; number: number; user: { login: string } }; release?: { tag_name: string; name: string | unknown; body: string | unknown; html_url: string; author: { login: string } }; issue?: { title: string; body: string | unknown; html_url: string; url: string; number: number; state: string; labels?: Array<{ name: string }>; user: { login: string } }; milestone?: { title: string; description: string | unknown; html_url: string; state: string; due_on: string | unknown; open_issues: number; closed_issues: number }; repository: { full_name: string } }, unknown, { topic: 'github.pr_merged'; data: never } | { topic: 'github.release_published'; data: never } | { topic: 'github.issue_closed'; data: never } | { topic: 'github.milestone_closed'; data: never }>
    'UpdateDraft': ApiRouteHandler<{ content?: string; platform?: 'twitter' | 'linkedin' | 'discord'; scheduledFor?: string }, unknown, never>
    'SingleDraft': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ProcessDrafts': EventHandler<never, never>
    'ListDrafts': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DeleteDraft': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreateDraft': ApiRouteHandler<{ content: string; platform: 'twitter' | 'linkedin' | 'discord' }, unknown, { topic: 'draft.created'; data: never }>
    'GetStats': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetRecentEvents': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AnalyzePR': EventHandler<never, { topic: 'draft.created'; data: never }>
    'AnalyzeActivity': EventHandler<never, { topic: 'draft.created'; data: never }>
  }
    
}